---
image:
  source_image_family: ubuntu-2404-lts-arm64
  project_id: "taskcluster-imaging"
  workload_identity_provider_project_number: 324168772199
  image_name: gw-fxci-gcp-l1-2404-arm64-headless-googlecompute-alpha
  zone: us-central1-a
vm:
  disk_size: 60
  taskcluster_version: 96.5.2
  tc_arch: ARM64
  script_paths:
  - "scripts/linux/ubuntu-2404-headless-arm64-headless"
