---
image:
  publisher: MicrosoftWindowsDesktop
  offer: windows11preview-arm64
  sku: win11-25h2-ent
  version: latest
sharedimage:
  gallery_name: "win11_a64_25h2_tester_alpha"
  image_name: "win11_a64_25h2_tester_alpha"
  image_version: 1.0.0
azure:
  managed_image_resource_group_name: rg-packer-worker-images
  managed_image_storage_account_type: Standard_LRS
  build_location: eastus
  locations:
    - centralus
vm:
  puppet_version: 8.10.0
  openvox_version: 8.19.2
  git_version: 2.53.0
  size: Standard_E8pds_v5
  tags:
    base_image: win11a6425h2azuretester
    worker_pool_id: win11-a64-25h2-tester
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: "master"
    deploymentId: "NA"
    managed_by: packer
tests:
  - error_reporting.tests.ps1
  - suppress_dialog_boxes.tests.ps1
  - files_system_management.tests.ps1
  - firewall.tests.ps1
  - network.tests.ps1
  - ntp.tests.ps1
  - power_management.tests.ps1
  - scheduled_tasks.tests.ps1
  - azure_vm_agent.tests.ps1
  - logging.tests.ps1
  - mercurial.tests.ps1
  - git.tests.ps1
  - mozilla_build.tests.ps1
  - mozilla_maintenance_service.tests.ps1
  - windows_worker_runner.tests.ps1
  - disable_services.tests.ps1
  - microsoft_wptx64.tests.ps1
