run-name: GCP - ${{ github.event.inputs.config }}
name: FXCI - GCP

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - gw-fxci-gcp-l1-2404-gui-alpha
        - gw-fxci-gcp-l1-2404-headless-alpha
        - gw-fxci-gcp-l1-2404-arm64-headless-alpha
        - trusted-gw-fxci-gcp-l3-2404-headless-alpha
        - trusted-gw-fxci-gcp-l3-2404-arm64-headless-alpha

permissions:
  id-token: write
  contents: read

jobs:
  check-access:
    name: "Verify User Access"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Load Authorized Users and Check Access
        shell: pwsh
        run: |
          $AUTHORIZED_USERS=$(Get-Content .github/relsre.json | Convertfrom-Json)
          if ($authorized_users -contains "${{ github.actor }}") {
            Write-host "User ${{ github.actor }} is authorized."
          }
          else {
            Write-Host "User ${{ github.actor }} is unauthorized."
            exit 1
          }
  setproject:
    needs: check-access
    name: "Get Project ID & ImageName from Config"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - id: set-matrix
        shell: pwsh
        run: |
          Import-Module ${{ github.workspace }}\bin\WorkerImages\WorkerImages.psm1
          Set-GCPWorkerImageName -Key '${{ github.event.inputs.config }}'
          Set-GCPWorkerImageProject -Key '${{ github.event.inputs.config }}'
    outputs:
      IMAGENAME: ${{ steps.set-matrix.outputs.IMAGENAME }}
      PROJECT: ${{ steps.set-matrix.outputs.PROJECT }}
  packer:
    needs: setproject
    name: "GCP ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093'
        id: auth
        with:
          workload_identity_provider: "projects/324168772199/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "deploy-prod@${{ needs.setproject.outputs.PROJECT }}.iam.gserviceaccount.com"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db'
      - name: 'Run Packer'
        shell: pwsh
        run: |
          Import-Module ${{ github.workspace }}\bin\WorkerImages\WorkerImages.psm1
          $Vars = @{
            github_token = "${{ secrets.GITHUB_TOKEN }}"
            Key = '${{ github.event.inputs.config }}'
          }
          New-GCPWorkerImage @Vars
  wiz:
    needs: [packer, setproject]
    name: "Wiz scan ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ !contains(github.event.inputs.config, 'trusted') }}
    steps:
      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli
      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      - name: Run wiz-cli scan
        run: |
          ./wizcli vm-image scan \
          --id ${{ needs.setproject.outputs.IMAGENAME }} \
          --region us-west1 \
          --subscriptionId ${{ needs.setproject.outputs.PROJECT }} \
          --secrets \
          --show-vulnerability-details \
          --policy-hits-only